# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifs', '0004_notification_setcountdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setcountdown', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='setcountdown',
        ),
    ]
